//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C36A0_JCIYPEntities : DbContext
    {
        public C36A0_JCIYPEntities()
            : base("name=C36A0_JCIYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_人員> SYS_人員 { get; set; }
        public virtual DbSet<SYS_流水號資料表> SYS_流水號資料表 { get; set; }
        public virtual DbSet<SYS_單位> SYS_單位 { get; set; }
        public virtual DbSet<行業分類> 行業分類 { get; set; }
        public virtual DbSet<產品分類> 產品分類 { get; set; }
        public virtual DbSet<會員_其他單位分類> 會員_其他單位分類 { get; set; }
        public virtual DbSet<會員分類> 會員分類 { get; set; }
        public virtual DbSet<會員產品> 會員產品 { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<i_Adr_zh_TW_Data> i_Adr_zh_TW_Data { get; set; }
        public virtual DbSet<i_Currency> i_Currency { get; set; }
        public virtual DbSet<i_IDX> i_IDX { get; set; }
        public virtual DbSet<i_Lang> i_Lang { get; set; }
        public virtual DbSet<i_Parm> i_Parm { get; set; }
        public virtual DbSet<i_SN> i_SN { get; set; }
        public virtual DbSet<i_UserLoginLog> i_UserLoginLog { get; set; }
        public virtual DbSet<i_WebCount> i_WebCount { get; set; }
        public virtual DbSet<i_WebVisitData> i_WebVisitData { get; set; }
        public virtual DbSet<會員> 會員 { get; set; }
        public virtual DbSet<最新消息> 最新消息 { get; set; }
        public virtual DbSet<最新消息分類> 最新消息分類 { get; set; }
        public virtual DbSet<活動花絮內容> 活動花絮內容 { get; set; }
        public virtual DbSet<活動花絮分類> 活動花絮分類 { get; set; }
        public virtual DbSet<活動花絮主檔> 活動花絮主檔 { get; set; }
        public virtual DbSet<文件管理> 文件管理 { get; set; }
    }
}
