//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    public partial class m_SYS_人員 :BaseEntityTable {
    public int SN { get; set; }
    public Nullable<int> UID { get; set; }
    public Nullable<int> PID { get; set; }
    public string PName { get; set; }
    public string LoginName { get; set; }
    public string LoginPwd { get; set; }
    public string Email { get; set; }
    public Nullable<int> Permission { get; set; }
    public string Remark { get; set; }
    }
}
