//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class 活動花絮主檔 : BaseEntityTable
    {
        public 活動花絮主檔()
        {
            this.活動花絮內容 = new HashSet<活動花絮內容>();
        }
    
        public int 流水號 { get; set; }
        public int 分類 { get; set; }
        public string 標題 { get; set; }
        public string 內容 { get; set; }
        public int 排序 { get; set; }
        public bool 顯示狀態Flag { get; set; }
        public System.DateTime 活動日期 { get; set; }
        public Nullable<System.DateTime> 修改日期 { get; set; }
        public Nullable<int> 點閱率 { get; set; }
        public Nullable<int> 新增人員 { get; set; }
        public Nullable<int> 修改人員 { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<活動花絮內容> 活動花絮內容 { get; set; }
    	[JsonIgnore]
        public virtual 活動花絮分類 活動花絮分類 { get; set; }
    }
}
